# **Notebook 6 – Outlier Treatment**

In [1]:
import pandas as pd
df = pd.read_csv("student_performance_dataset.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             4000 non-null   object
 1   Age                    4000 non-null   int64
 2   Study_Hours            4000 non-null   float64
 3   Attendance_Percentage  4000 non-null   float64
 4   Assignment_Score       4000 non-null   float64
 5   Midterm_Score          4000 non-null   float64
 6   Final_Score            4000 non-null   float64
 7   Projects_Completed     4000 non-null   int64
 8   Sleep_Hours            4000 non-null   float64
 9   Screen_Time_Hours      4000 non-null   float64
 10  Study_Expenses         4000 non-null   float64
 11  Travel_Distance_Km     4000 non-null   float64
dtypes: float64(9), int64(2), object(1)
memory usage: 375.1+ KB

## **1. What is an Outlier?**



**Understand the Concept**

- An outlier is a data value that is very different from most other values.
- Outliers can be unusually high or unusually low.
- An outlier is not always an error; it can be a valid extreme observation.

**Demonstrate the Concept**

**Example:**

- Check unusually high or low Study_Hours values.

**AI/ML Usage:**

- Helps decide the appropriate treatment for extreme values.

In [9]:
# Implement the Concept
# study hours
df["Study_Hours"].describe()

count    4000.000000
mean        5.455325
std         2.264473
min        -4.000000
25%         3.900000
50%         5.400000
75%         6.900000
max        30.000000
Name: Study_Hours, dtype: float64

**Explanation**

- describe() gives summary statistics for Study_Hours.
- It shows the minimum, maximum, mean, and quartile values.

## **2. Outlier vs Error**



**Understand the Concept**

- An outlier is an unusual value, but it can be valid.
- An error is an incorrect or impossible value.

**Demonstrate the Concept**

**Example:**

- A study time of 14 hours may be valid, while -5 hours is an error.

**AI/ML Usage:**

- Helps choose the correct treatment for unusual observations.

In [18]:
# Implement the Concept
# Outlier 
Outlier = df[(df["Study_Hours"] == 0) |  (df["Study_Hours"] > 12)]
Outlier[["Student_ID", "Study_Hours"]].head(3)

    Student_ID  Study_Hours
5      STU0006         14.0
25     STU0026         13.5
115    STU0116         14.5

In [15]:
# Error 
df[df["Study_Hours"] < 0]

,Student_ID,Age,Study_Hours,Attendance_Percentage,Assignment_Score,Midterm_Score,Final_Score,Projects_Completed,Sleep_Hours,Screen_Time_Hours,Study_Expenses,Travel_Distance_Km
310,STU0311,23,-4.0,62.9,45.4,61.2,21.8,3,5.5,5.5,1952.66,10.3

**Explanation**

- The conditions find unusually low and high values.
- Negative study hours indicate an error.

## **3. IQR Method**


**Understand the Concept**

- IQR method identifies outliers using the first quartile and third quartile.
- IQR is calculated as the difference between Q3 and Q1.
- Values below the lower limit or above the upper limit are treated as potential outliers.

**Demonstrate the Concept**

**Example:**

- Use the IQR method to detect outliers in study hours.

**AI/ML Usage:**

- Helps identify extreme values before model training.

In [19]:
# Implement the Concept
# quartiles
Q1 = df["Study_Hours"].quantile(0.25)
Q3 = df["Study_Hours"].quantile(0.75)

# IQR
IQR = Q3 - Q1

# limits
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# outliers
outliers = df[(df["Study_Hours"] < lower) | (df["Study_Hours"] > upper)]
print("Lower Limit:", lower)
print("Upper Limit:", upper)
print("Outliers:", len(outliers))

Lower Limit: -0.600000000000001
Upper Limit: 11.400000000000002
Outliers: 21

In [21]:
outliers[["Student_ID", "Study_Hours"]].tail(3)

     Student_ID  Study_Hours
3202    STU3203         12.0
3295    STU3296         11.6
3698    STU3699         11.8

**Explanation**

- Q1 and Q3 define the middle 50% of the data.
- IQR is used to calculate the lower and upper limits.
- Values outside these limits are identified as potential outliers.

## **4. Z-Score Method**



**Understand the Concept**

- Z-score shows how far a value is from the mean in terms of standard deviations.
- A value with a very high or low Z-score can be considered a potential outlier.
- Commonly, values with an absolute Z-score greater than 3 are treated as outliers.

**Demonstrate the Concept**

**Example:**

- Use Z-score to find extreme study hour values.

**AI/ML Usage:**

- Helps detect extreme values before model training.

In [22]:
# Implement the Concept
# Z-score
mean = df["Study_Hours"].mean()
std = df["Study_Hours"].std()
z_score = (df["Study_Hours"] - mean) / std

# outliers
outliers = df[z_score.abs() > 3]
print("Outliers:", len(outliers))

Outliers: 11

In [23]:
outliers[["Student_ID", "Study_Hours"]].sample(3)

    Student_ID  Study_Hours
115    STU0116         14.5
311    STU0312         30.0
411    STU0412         13.0

**Explanation**

- Mean and standard deviation are used to calculate the Z-score.
- abs() checks the distance from the mean in both directions.
- Values with an absolute Z-score above 3 are identified as potential outliers.

## **5. Percentile Method**



**Understand the Concept**

- The Percentile Method identifies extreme values using selected percentile limits.
- Values below the lower percentile or above the upper percentile are treated as potential outliers.

**Demonstrate the Concept**

**Example:**

- Use the 1st and 99th percentiles to find extreme study hour values.

**AI/ML Usage:**

- Helps identify extreme values before model training.

In [24]:
# Implement the Concept
# percentiles
lower = df["Study_Hours"].quantile(0.01)
upper = df["Study_Hours"].quantile(0.99)

# Find outliers
outliers = df[(df["Study_Hours"] < lower) | (df["Study_Hours"] > upper)]
print("Lower Limit:", lower)
print("Upper Limit:", upper)
print("Outliers:", len(outliers))

Lower Limit: 0.5
Upper Limit: 10.8
Outliers: 38

In [26]:
outliers[["Student_ID", "Study_Hours"]].sample(4)

     Student_ID  Study_Hours
1452    STU1453         11.0
310     STU0311         -4.0
3011    STU3012         11.7
3335    STU3336         11.1

**Explanation**

- quantile() finds the selected percentile values.
- The lower and upper limits define the extreme range.

## **6. Winsorization**



**Understand the Concept**

- Winsorization reduces the effect of extreme values by replacing them with selected percentile limits.
- It keeps the records but changes extreme values to less extreme values.

**Should it be capped?**
- Yes, when valid extreme values are present but have too much influence on the analysis.

**Why?**
- It reduces the impact of extreme values without removing the observations.

**Demonstrate the Concept**

**Example:**

- Replace values below the 1st percentile and above the 99th percentile.

**AI/ML Usage:**

- Helps reduce the influence of extreme values while retaining the data.

In [33]:
# Implement the Concept
# limits
lower = df["Study_Hours"].quantile(0.01)
upper = df["Study_Hours"].quantile(0.99)

# Apply Winsorization
outliers["Study_Hours_Winsorized"] = df["Study_Hours"].clip(lower, upper)

# Compare values
outliers[["Student_ID","Study_Hours","Study_Hours_Winsorized"]].sample(5)

C:\Users\iamna\AppData\Local\Temp\ipykernel_31880\3133512662.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  outliers["Study_Hours_Winsorized"] = df["Study_Hours"].clip(lower, upper)

     Student_ID  Study_Hours  Study_Hours_Winsorized
3698    STU3699         11.8                    10.8
410     STU0411         12.5                    10.8
5       STU0006         14.0                    10.8
3028    STU3029         11.7                    10.8
311     STU0312         30.0                    10.8

**Explanation**

- quantile() finds the lower and upper limits.
- clip() replaces extreme values with those limits

## **7. Capping**



**Understand the Concept**

- Capping limits extreme values by replacing them with a fixed upper or lower boundary.
- It keeps the records while reducing the effect of extreme values.

**Should it be capped?**
- Cap the value when it is valid but has too much influence on the analysis.

**Why?**
- Capping controls extreme values without removing the observations.

**Demonstrate the Concept**

**Example:**

- Limit extreme Study_Hours values to the selected upper and lower limits.

**AI/ML Usage:**

- Helps reduce the effect of extreme values on ML models.

In [34]:
# Implement the Concept
# limits
lower = df["Study_Hours"].quantile(0.01)
upper = df["Study_Hours"].quantile(0.99)

# Apply capping
outliers["Study_Hours_Capped"] = df["Study_Hours"].clip(lower, upper)

# Show results
outliers[["Student_ID","Study_Hours","Study_Hours_Capped"]].sample(5)

C:\Users\iamna\AppData\Local\Temp\ipykernel_31880\4003266987.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  outliers["Study_Hours_Capped"] = df["Study_Hours"].clip(lower, upper)

     Student_ID  Study_Hours  Study_Hours_Capped
3028    STU3029         11.7                10.8
1196    STU1197         11.0                10.8
2234    STU2235         12.0                10.8
411     STU0412         13.0                10.8
25      STU0026         13.5                10.8

**Explanation**

- quantile() sets the lower and upper limits.
- clip() replaces values outside the limits.

## **8. Flooring**



**Understand the Concept**

- Flooring replaces values below a selected lower limit with that limit.
- It reduces the effect of unusually low values while keeping the records.

**Demonstrate the Concept**

**Example:**

- Set a minimum limit for Study_Hours and replace lower values.

**AI/ML Usage:**

- Helps reduce the effect of unusually low values on ML models.

In [35]:
# Implement the Concept
# lower limit
lower = df["Study_Hours"].quantile(0.01)

# Apply flooring
outliers["Study_Hours_Floored"] = df["Study_Hours"].clip(lower=lower)

# Show results
outliers[["Student_ID","Study_Hours","Study_Hours_Floored"]].head(10)

C:\Users\iamna\AppData\Local\Temp\ipykernel_31880\879472460.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  outliers["Study_Hours_Floored"] = df["Study_Hours"].clip(lower=lower)

    Student_ID  Study_Hours  Study_Hours_Floored
5      STU0006         14.0                 14.0
25     STU0026         13.5                 13.5
55     STU0056         11.4                 11.4
115    STU0116         14.5                 14.5
310    STU0311         -4.0                  0.5
311    STU0312         30.0                 30.0
312    STU0313         25.0                 25.0
410    STU0411         12.5                 12.5
411    STU0412         13.0                 13.0
412    STU0413         12.8                 12.8

**Explanation**

- quantile() finds the lower limit.
- clip() replaces values below the limit.

## **9. Transformation**



**Understand the Concept**

- Transformation changes the scale or distribution of data to reduce the effect of extreme values.
- Log transformation is commonly used for highly skewed numerical data.

**Demonstrate the Concept**

**Example:**

- Apply log transformation to Study_Expenses.

**AI/ML Usage:**

- Helps improve model performance when numerical features are highly skewed.

In [39]:
# Implement the Concept
import numpy as np
# Apply log transformation
df["Study_Expenses_Log"] = np.log(df["Study_Expenses"])

# Show results
df[["Student_ID","Study_Expenses","Study_Expenses_Log"]].tail()

C:\Users\iamna\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

     Student_ID  Study_Expenses  Study_Expenses_Log
3995    STU3996         2179.42            7.686814
3996    STU3997         1565.47            7.355941
3997    STU3998         4188.59            8.340119
3998    STU3999         1722.30            7.451416
3999    STU4000         1426.38            7.262895

**Explanation**

- log() applies a log transformation.
- It reduces the effect of very large values.

## **10. Removing Outliers**



**Understand the Concept**

- Removing outliers means deleting observations that are confirmed to be incorrect or unsuitable for the analysis.
- Outliers should not be removed automatically because some extreme values may be valid.


**Is it a valid extreme observation?**
- Do not remove it when the extreme value is realistic and meaningful.

**Should it be removed?**
- Remove only when there is a clear reason, such as a data-entry error.

**Why?**
- Removing valid extreme observations can cause information loss and may make the dataset less representative.

**Demonstrate the Concept**

**Example:**

- Remove study hour values that are negative or clearly invalid.

**AI/ML Usage:**

- Helps prevent incorrect extreme values from affecting model training.

In [40]:
# Implement the Concept
# invalid values
invalid = df[df["Study_Hours"] < 0]
print("Invalid Outliers:", len(invalid))

# Remove invalid values
df_clean = df[df["Study_Hours"] >= 0]
print("Rows Before:", len(df))
print("Rows After:", len(df_clean))

Invalid Outliers: 1
Rows Before: 4000
Rows After: 3999

**Explanation**

- The condition finds negative study hour values.
- These values are treated as errors.
- Only the confirmed invalid records are removed.